/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const MoodEntry = IDL.Record({
  'emotionTags' : IDL.Vec(IDL.Text),
  'notes' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
  'moodScore' : IDL.Nat8,
});
export const Sender = IDL.Variant({ 'bot' : IDL.Null, 'user' : IDL.Null });
export const ChatMessage = IDL.Record({
  'sender' : Sender,
  'message' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMoodEntry' : IDL.Func(
      [IDL.Nat8, IDL.Vec(IDL.Text), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllMoodEntries' : IDL.Func([], [IDL.Vec(MoodEntry)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChatHistory' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getConsentTimestamp' : IDL.Func([], [IDL.Opt(Time)], ['query']),
  'getLatestMoodEntry' : IDL.Func([], [IDL.Opt(MoodEntry)], ['query']),
  'getRecentMoodEntries' : IDL.Func([], [IDL.Vec(MoodEntry)], ['query']),
  'hasConsented' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveChatMessage' : IDL.Func([Sender, IDL.Text], [], []),
  'saveConsent' : IDL.Func([IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const MoodEntry = IDL.Record({
    'emotionTags' : IDL.Vec(IDL.Text),
    'notes' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
    'moodScore' : IDL.Nat8,
  });
  const Sender = IDL.Variant({ 'bot' : IDL.Null, 'user' : IDL.Null });
  const ChatMessage = IDL.Record({
    'sender' : Sender,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMoodEntry' : IDL.Func(
        [IDL.Nat8, IDL.Vec(IDL.Text), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllMoodEntries' : IDL.Func([], [IDL.Vec(MoodEntry)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChatHistory' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getConsentTimestamp' : IDL.Func([], [IDL.Opt(Time)], ['query']),
    'getLatestMoodEntry' : IDL.Func([], [IDL.Opt(MoodEntry)], ['query']),
    'getRecentMoodEntries' : IDL.Func([], [IDL.Vec(MoodEntry)], ['query']),
    'hasConsented' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveChatMessage' : IDL.Func([Sender, IDL.Text], [], []),
    'saveConsent' : IDL.Func([IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };