/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'sender' : Sender,
  'message' : string,
  'timestamp' : Time,
}
export interface MoodEntry {
  'emotionTags' : Array<string>,
  'notes' : [] | [string],
  'timestamp' : Time,
  'moodScore' : number,
}
export type Sender = { 'bot' : null } |
  { 'user' : null };
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMoodEntry' : ActorMethod<
    [number, Array<string>, [] | [string]],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllMoodEntries' : ActorMethod<[], Array<MoodEntry>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatHistory' : ActorMethod<[], Array<ChatMessage>>,
  'getConsentTimestamp' : ActorMethod<[], [] | [Time]>,
  'getLatestMoodEntry' : ActorMethod<[], [] | [MoodEntry]>,
  'getRecentMoodEntries' : ActorMethod<[], Array<MoodEntry>>,
  'hasConsented' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveChatMessage' : ActorMethod<[Sender, string], undefined>,
  'saveConsent' : ActorMethod<[boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];